# Site settings
title: Bhagyesh Pathak
email: ""
description: >-
  A collection of essays and resources on technology, philosophy, and human potential.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bhagyeshpathak.com" # the base hostname & protocol for your site, e.g. http://example.com
google_site_verification: ""
# Build settings
markdown: kramdown

# Collections
# collections:
#   resources:
#     output: true
#     permalink: /resources/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  # - scope:
  #     path: ""
  #     type: "resources"
  #   values:
  #     layout: "resource"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

plugins:
  - jekyll-sitemap    # Helps with SEO and site indexing
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md
  - .specstory

